ntp_config_set: add argument number guard

diff --git a/src/wp360-codesys-bridge b/src/wp360-codesys-bridge
--- a/src/wp360-codesys-bridge
+++ b/src/wp360-codesys-bridge
@@ -121,6 +121,11 @@ case "$1" in
     echo "$NTP\r\n$Servers\r\n$Fallback"
     ;;
   ntp_config_set)
+    if [ "$#" -ne "4" ]
+    then
+      echo "ntp_config_set: 4 arguments required, $# provided"
+      exit 1
+    fi
     NTP="$2"
     SERVER="$3"
     FALLBACK="$4"
